#+TITLE: Virtual Labs Platform
#+AUTHOR: VLEAD
#+DATE: [2016-11-08 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction

  [[https://docs.google.com/drawings/d/1s_expWC1QOMXOHgLJHW40OB04FvJt--1vwpSVjhdoGY/edit?ts=5834280f][=Virtual Labs platform=]] is a slew of services collaborating with each other
  while providing a mechanism to author and deliver content of Virtual Labs.
  
  lab data service(lds), content service, experiment service and translators
  make up the core of the platform.  Each experiment or a lab has a
  specification detailing the structure of an experiment or a lab and this
  specification is the glue between authored content and delivered content.

* Motivation

  While writing this document, Virtual Labs is using Open
  edX as the platform for serving virtual labs.  Open edX
  platform is both a:
  - learning management system (LMS), LMS provides features
    that allow an instructor to manage the learning of
    students by setting up a learning plan, evaluation,
    fixing dates for submission of home works, etc.
  - content management server (CMS), CMS allows content to
    be added, edited and served.

  Though =Virtual Labs= is happy to leverage the features of
  LMS - single-sign-on, persistence, uniform UI, the CMS
  becomes a bottleneck since content editing is done through
  Open Edx studio.  The tying of content editing through the
  studio undermines the freedom of using different editors
  and formats that are more flexible to generate content -
  read as html - that a browser can interpret.

  Apart from untethering the content creation from the
  hosting platform, the platform should be able to provide
  other services like single sign on, persistence, analytics
  and uniform user interface.

* [[./requirements.org][Requirements]]

* [[./design.org][Design]]

* Other services
  1. Translators
  2. Resource Generator
  3. Content Server
